// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/course-save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/course-save.post').default>>>>
    }
    '/api/admin/user-update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/user-update.post').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/course/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/course/[id].get').default>>>>
    }
    '/api/course': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/course/index.get').default>>>>
    }
    '/api/progress/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/progress/me.get').default>>>>
    }
    '/api/progress/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/progress/save.post').default>>>>
    }
    '/api/tts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tts.get').default>>>>
    }
    '/images/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/images/[...path].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}