// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04/09/2026, 00.01.47
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/projects/edtech/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/plugins/**/*.{js,ts,mjs}","D:/projects/edtech/composables/**/*.{js,ts,mjs}","D:/projects/edtech/utils/**/*.{js,ts,mjs}","D:/projects/edtech/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/projects/edtech/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;